name: CI-DockerBuild

on: 
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-and-deploy:
    uses: danielopezh/devops-pipelines/.github/workflows/docker-workflow.yaml@main
    with:
      docker_image_name: os
      micro_name: microservicio-1
      docker_file: ./py/Dockerfile
    secrets: inherit